config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :groups, only: %i[index new create] do
    resources :operations, only: %i[index]
  end
  resources :operations, only: %i[new create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, author_id: user.id
    can :manage, Operation, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :operations

  validates :name, presence: true, length: { in: 1..100 }
  validates :icon, presence: true, length: { in: 1..300 }
end

app/models/groups_operation.rb
class GroupsOperation < ApplicationRecord
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: { in: 1..100 }
  validates :amount, numericality: { greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :operations

  validates :name, presence: true, length: { in: 1..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from 'CanCan::AccessDenied' do |_exception|
    redirect_to root_path, alert: 'You are not authorized to access that page.'
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @groups = Group.where(author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Successfully created a group.'
    else
      flash[:alert] = 'Failed to create a group.'
      render :new
    end
  end

  private

  def group_params
    gp = params.require(:group).permit(:name, :icon)
    gp[:author_id] = current_user.id
    gp
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to groups_path if current_user
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  load_and_authorize_resource

  def index
    @group = Group.find_by(id: params[:group_id])
    @operations = helpers.find_operations
  end

  def new
    @operation = Operation.new
  end

  def create
    @operation = Operation.new(operation_params)

    helpers.create_groups_operations(@operation, params[:group][:group_id])

    if @operation.save
      redirect_to groups_path, notice: 'Successfully created an operation.'
    else
      flash[:alert] = 'Failed to create an operation.'
      render :new
    end
  end

  private

  def operation_params
    op = params.require(:operation).permit(:name, :amount)
    op[:author_id] = current_user.id
    op
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_amount(group)
    total_amount = 0

    group.operations.each do |operation|
      total_amount += operation.amount
    end
    total_amount
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
  def find_operations
    operations = []
    groups_operations = GroupsOperation.where(group_id: params[:group_id]).order(created_at: :desc)
    groups_operations.each do |group_operation|
      operations << Operation.find_by(id: group_operation.operation_id)
    end
    operations
  end

  def create_groups_operations(operation, array)
    i = 1

    while i < array.length
      group = Group.find_by(id: array[i])
      operation.groups << group
      i += 1
    end
  end
end

app/views/groups/index.html.erb
<header class="header container primary-gradient-background">
  <h1>Groups</h1>
</header>
<section>
  <% if @groups.empty? %>
    <div class="information padding border">
      <h3 class="text-center">No groups yet.</h3>
    </div>
  <% else %>
  <% @groups.each do |group| %>
    <div class="d-flex information border gap">
      <img src=<%= group.icon %> alt=<%= group.name %> class="icon">
      <div class="container flex-fill justify-content-between">
        <div class="d-flex justify-content-between">
          <h3><%= link_to group.name, group_operations_path(group_id: group.id) %></h3>
          <p>$<%= group_amount(group) %></p>
        </div>
        <small>
          <%= group.created_at.strftime("%d %b %Y") %>
        </small>
      </div>
    </div>
  <% end %>
  <% end %>
  <div class="margin">
    <%= link_to "Add group", new_group_path, class: "btn" %>
  </div>
</section>

app/views/groups/new.html.erb
<header class="header container primary-gradient-background">
  <h1 class="position-absolute">
    <%= link_to groups_path do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>
  </h1>
  <h1 class="text-center margin-y">Create Group</h1>
</header>

<%= form_with model: @group, data: { turbo: false }, class: "container form margin-y border-y" do |form| %>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, autofocus: true, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :icon, class: "form-label" %>
    <%= form.text_field :icon, class: "form-control", required: true %>
  </div>

  <%= form.submit "Save", class: "btn align-self-start margin-y" %>

<% end %>

app/views/home/index.html.erb
<header class="header container primary-gradient-background">
  <h1>Fast Budget</h1>
</header>
<section class="information container border">
  <div class="container margin-b">
    <h2 class="heading">How it works</h2>
    <p>
      Easily manage your budget. Have a list of transactions associated with a category, so that you can see how much money you spent and on what.
    </p>
  </div>

  <div class="container margin-b">
    <h2 class="heading">Join now</h2>
    <p>
      If you haven't already, <%= link_to "sign up now", new_user_registration_path, class: "link" %> or if you already have an account, <%= link_to "sign in", new_user_session_path, class: "link" %>.
    </p>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FastBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/operations/index.html.erb
<header class="header container primary-gradient-background position-relative">
  <h1 class="position-absolute">
    <%= link_to groups_path do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>
    </h1>
  <h1 class="text-center margin-y">Operations for <%= @group.name %></h1>
</header>
<section>
  <div class="money-amount">
    <p  class="text-center">Money spent: $<%= group_amount(@group) %></p>
  </div>
  <% if @operations.empty? %>
    <div class="information padding border">
      <h3 class="text-center">No operations yet.</h3>
    </div>
  <% else %>
    <% @operations.each do |operation| %>
      <div class="information d-flex justify-content-evenly padding border">
        <h3><%= operation.name %></h3>
        <p>$<%= operation.amount %></p>
      </div>
    <% end %>
  <% end %>
  <div class="margin">
    <%= link_to "Add operation", new_operation_path, class: "btn" %>
  </div>
</section>

app/views/operations/new.html.erb
<header class="header container primary-gradient-background">
  <h1 class="position-absolute">
    <%= link_to :back do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>
    </h1>
  <h1 class="text-center margin-y">Create Operation</h1>
</header>

<%= form_with model: @operation, data: { turbo: false }, class: "container form margin-y border-y" do |form| %>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, autofocus: true, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :group, class: "form-label" %>
    <%= select("group", "group_id", Group.all.collect { |g| [ g.name, g.id ] }, { include_blank: false }, multiple: true, size: 3, class: "form-control", required: true) %>
  </div>

  <%= form.submit "Save", class: "btn align-self-start margin-y" %>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="notice-container">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert-container">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>